name: CI
on: [pull_request]
jobs:
  static_analysis:
    name: Static analysis with phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - uses: "ramsey/composer-install@v2"

      - run: composer require --dev phpstan/phpstan

      - run: vendor/bin/phpstan analyse

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2']
    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-values: error_reporting=E_ALL

      - run: ./travisci/bin/start.sh

      - uses: "ramsey/composer-install@v2"

      - run: |
          ./travisci/bin/logs.sh
          vendor/bin/phpunit --debug

      - run: ./travisci/bin/stop.sh
